hotspot/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
	url(r"^admin/", admin.site.urls),
	
	# VIEWS
	url(r"^$", views.index),


	# API
	url(r"^api/hotspots/$", views.api_hotspots),
	url(r"^api/hotspots/area/$", views.api_hotspots_area),
	url(r"^api/hotspot/$", views.api_hotspot),
	url(r"^api/hotspot/content/$", views.api_hotspot_content),
	
	url(r"^api/clusters/$", views.api_clusters),
	url(r"^api/clusters/grid/$", views.api_clusters_grid),
]

hotspot/models.py
import os
import uuid
import math
import enum
import datetime
import decimal

from django.db import models
from django.db.models.signals import post_save, pre_init
from django.dispatch import receiver
from django import forms
from django.contrib import admin
from django.utils import timezone
 
from . import settings

########################################################
## CLUSTER MODEL

CLUSTERS_LIMIT  = 50
CLUSTERS_UPDATE = 20

# geo_lat
CLUSTER_HEIGHT = decimal.Decimal(0.1)
CLUSTER_HEIGHT_HALF = CLUSTER_HEIGHT / decimal.Decimal(2)
CLUSTER_HEIGHT_QUARTER = CLUSTER_HEIGHT_HALF / decimal.Decimal(2)
CLUSTER_HEIGHT_ROUND = 1

# geo_long
CLUSTER_WIDTH = decimal.Decimal(0.1)
CLUSTER_WIDTH_HALF = CLUSTER_WIDTH / decimal.Decimal(2)
CLUSTER_WIDTH_QUARTER = CLUSTER_WIDTH_HALF / decimal.Decimal(2)
CLUSTER_WIDTH_ROUND = 1

CLUSTER_UPDATE_DELTA = datetime.timedelta(hours=2) # after 2 hours, cluster dirty
CLUSTER_UPDATE_REQUESTS = 1000 # after 1000 requests, cluster dirty

class ClusterModel(models.Model):

	uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	geo_lat  = models.DecimalField(default=0, max_digits=12, decimal_places=6)
	geo_long = models.DecimalField(default=0, max_digits=12, decimal_places=6)
	
	top          = models.ForeignKey("ClusterModel", on_delete=models.DO_NOTHING, related_name="+", blank=True, null=True)
	left_top     = models.ForeignKey("ClusterModel", on_delete=models.DO_NOTHING, related_name="+", blank=True, null=True)
	left         = models.ForeignKey("ClusterModel", on_delete=models.DO_NOTHING, related_name="+", blank=True, null=True)
	left_bottom  = models.ForeignKey("ClusterModel", on_delete=models.DO_NOTHING, related_name="+", blank=True, null=True)
	right_top    = models.ForeignKey("ClusterModel", on_delete=models.DO_NOTHING, related_name="+", blank=True, null=True)
	right        = models.ForeignKey("ClusterModel", on_delete=models.DO_NOTHING, related_name="+", blank=True, null=True)
	right_bottom = models.ForeignKey("ClusterModel", on_delete=models.DO_NOTHING, related_name="+", blank=True, null=True)
	bottom       = models.ForeignKey("ClusterModel", on_delete=models.DO_NOTHING, related_name="+", blank=True, null=True)

	updated = models.PositiveIntegerField(default=0)         # times this cluster updated
	last_update = models.DateTimeField(default=timezone.now) # date and time of last update
	total_requests = models.PositiveIntegerField(default=0)  # total requests
	requests = models.PositiveIntegerField(default=0)        # requests since last update

	#class Meta:
	#	unique_together = (("geo_lat","geo_long"))

	def __str__(self):
		return "Cluster[" + str(self.geo_lat) + "," + str(self.geo_long) + "]"

	def dirty(self):
		b = (timezone.now() + CLUSTER_UPDATE_DELTA < self.last_update ) or \
		(self.requests >= CLUSTER_UPDATE_REQUESTS) or \
		(self.updated == 0)
		return b

	def get_left_top(self):
		geo_lat  = self.geo_lat  - CLUSTER_HEIGHT_QUARTER
		geo_long = self.geo_long - CLUSTER_WIDTH_QUARTER
		return geo_lat, geo_long

	def get_right_top(self):
		geo_lat  = self.geo_lat  - CLUSTER_HEIGHT_QUARTER
		geo_long = self.geo_long + CLUSTER_WIDTH_QUARTER
		return geo_lat, geo_long

	def get_left_bottom(self):
		geo_lat  = self.geo_lat  + CLUSTER_HEIGHT_QUARTER
		geo_long = self.geo_long - CLUSTER_WIDTH_QUARTER
		return geo_lat, geo_long

	def get_right_bottom(self):
		geo_lat  = self.geo_lat  + CLUSTER_HEIGHT_QUARTER
		geo_long = self.geo_long + CLUSTER_WIDTH_QUARTER
		return geo_lat, geo_long

class ClusterModelAdmin(admin.ModelAdmin):
	model = ClusterModel
	list_display = ['geo_lat', 'geo_long', 'updated', 'last_update', 'total_requests', 'requests' ]

admin.site.register(ClusterModel, ClusterModelAdmin)

########################################################
## HOTSPOT MODEL

HOTSPOTMODEL_CATEGORY_CHOICES = (
	(0, "Unknown"),
	(1, "Hotel"),
	(2, "Food & Restaurant"),
	(3, "Entertainment"),
	(4, "Shop"),
	(5, "Travel"),
)

class HotspotModel(models.Model):

	uuid     = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	
	cluster  = models.ForeignKey(ClusterModel, on_delete=models.DO_NOTHING, related_name="hotspots", null=False, db_index=True)
	name     = models.CharField(max_length=2048, blank=False, null=False)
	geo_lat  = models.DecimalField(max_digits=12, decimal_places=6)
	geo_long = models.DecimalField(max_digits=12, decimal_places=6)
	category = models.PositiveIntegerField(default=0, null=False, blank=False, choices=HOTSPOTMODEL_CATEGORY_CHOICES)

	desc     = models.CharField(max_length=2048, blank=False, null=True)
	image    = models.URLField(max_length=2048,  blank=False, null=True)

	country  = models.CharField(max_length=2048, blank=False, null=True)
	city     = models.CharField(max_length=2048,  blank=False, null=True)
	zip      = models.CharField(max_length=2048,  blank=False, null=True)
	street   = models.CharField(max_length=2048, blank=False, null=True)
	phone    = models.CharField(max_length=2048, blank=False, null=True)
	url      = models.URLField(max_length=2048,  blank=False, null=True)
	url_fb   = models.URLField(max_length=2048,  blank=False, null=True)

	score    = models.DecimalField(max_digits=6, decimal_places=3, default=0)     # from 0 to 100
	plausibility = models.DecimalField(max_digits=6, decimal_places=3, default=0) # from 0 to 100
	updated = models.PositiveIntegerField(default=0) # times updated

	def __str__(self):
		return "Hotspot[" + str(self.name) + "|" + str(self.score) + "]"

	# calculate distance between this and a other hotspot in meters
	def distance(self, hotspot):
		geo_lat = math.radians(self.geo_lat - hotspot.geo_lat)
		geo_long = Math.toRadians(self.geo_long - hotspot.geo_long)
		a = math.sin(geo_lat/2) * math.sin(geo_lat/2) + \
			math.cos(math.radians(hotspot.geo_lat)) * math.cos(math.radians(selft.geo_lat)) * \
			math.sin(geo_long/2) * Math.sin(geo_long/2)
		return 6371000 * math.atan2(math.sqrt(a), math.sqrt(1-a))

class HotspotScoreModel(models.Model):
	uuid		= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

	spot		= models.ForeignKey(HotspotModel, default=None,	null=True, on_delete=models.CASCADE, db_index=True)
	#spot_uuid	= models.UUIDField(primary_key=False, editable=True)
	score_type	= models.PositiveIntegerField(default=0)
	score		= models.PositiveIntegerField(default=0)
	score_weight	= models.PositiveIntegerField(default=0)


class HotspotScoreModelAdmin(admin.ModelAdmin):
	model = HotspotScoreModel
	list_display = ['spot', 'score_type', 'score', 'score_weight' ]

#inline Score editing in hotspotmodel
class HotspotScoreModelInline(admin.TabularInline):
	model = HotspotScoreModel
	max_num = 2
	
admin.site.register(HotspotScoreModel, HotspotScoreModelAdmin)

class HotspotModelAdmin(admin.ModelAdmin):
	model = HotspotModel
	list_display = ['uuid', 'name', 'desc', 'category', 'score', 'plausibility' ] 
	inlines = [ HotspotScoreModelInline ]

admin.site.register(HotspotModel, HotspotModelAdmin)

class ScoreType(enum.Enum):
	Facebook = 1
	Yelp = 2

class HotspotType(enum.Enum):
	UNKNOWN = 0
	HOTEL_LODGING = 1
	FOOD_BEVERAGE = 2
	ARTS_ENTERTAINMENT = 3
	SHOPPING_RETAIL = 4
	TRAVEL_TRANSPORTATION = 5

	def __str__(self):
		return hotspot_type_string[self]

	def parse(string):
		string = string.lower().strip()

		# if it is in the dict, return type
		if string in hotspot_type_lookup:
			return hotspot_type_lookup[string].value

		# if not try each entry
		else:
			# the first substring in lookup dict. wins
			for key in hotspot_type_lookup:
				if key in string:
					return hotspot_type_lookup[key].value

			return HotspotType.UNKNOWN.value

hotspot_type_string = \
{
	HotspotType.UNKNOWN:               "UNKNOWN",
	HotspotType.HOTEL_LODGING:         "HOTEL_LODGING",
	HotspotType.FOOD_BEVERAGE:         "FOOD_BEVERAGE",
	HotspotType.ARTS_ENTERTAINMENT:    "ARTS_ENTERTAINMENT",
	HotspotType.SHOPPING_RETAIL:       "SHOPPING_RETAIL",
	HotspotType.TRAVEL_TRANSPORTATION: "TRAVEL_TRANSPORTATION",
}

hotspot_type_lookup = \
{
	# HOTEL_LODGING
	"hotel": HotspotType.HOTEL_LODGING,
	"lodging": HotspotType.HOTEL_LODGING,

	# FOOD_BEVERAGE
	"food": HotspotType.FOOD_BEVERAGE,
	"beverage": HotspotType.FOOD_BEVERAGE,

	# ARTS_ENTERTAINMENT
	"arts": HotspotType.ARTS_ENTERTAINMENT,
	"entertainment": HotspotType.ARTS_ENTERTAINMENT,

	# SHOPPING_RETAIL
	"shop": HotspotType.SHOPPING_RETAIL,
	"retail": HotspotType.SHOPPING_RETAIL,

	# TRAVEL_TRANSPORTATION
	"travel": HotspotType.TRAVEL_TRANSPORTATION,
	"transport": HotspotType.TRAVEL_TRANSPORTATION,
}

hotspot/views.py
import os
import datetime
import threading
import decimal
import math
import numpy
import random

from django import http, template
from django.http import HttpResponse, JsonResponse

from django.template.response import TemplateResponse
from django.template import TemplateDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone, html

from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser

from ratelimit.utils import is_ratelimited

from . import models, serializers, fetcher
from . import cluster as cl

# ------------------- VIEW ----------------------------

def index(request):
	return TemplateResponse(request, "index.html")

# ------------------- API -----------------------------

API_REQUEST_LIMIT = "1000/h"

def api_hotspots(request):

	if is_ratelimited(request, key="ip", rate=API_REQUEST_LIMIT, group="api", increment=True):
		return HttpResponse(status=429)

	hotspots = reversed(models.HotspotModel.objects.order_by("score"))

	data = {}
	data["type"] = "FeatureCollection"
	data["features"] = []

	for hotspot in hotspots:

		tmp = {}
		tmp["type"] = "Feature"
		tmp["geometry"] = {}
		tmp["geometry"]["type"] = "Point"
		tmp["geometry"]["coordinates"] = [hotspot.geo_long, hotspot.geo_lat]
		tmp["properties"] = {}
		tmp["properties"]["name"] = html.escape(hotspot.name)
		tmp["properties"]["uuid"] = str(hotspot.uuid)
		tmp["properties"]["desc"] = html.escape(hotspot.desc)
		tmp["properties"]["score"] = hotspot.score
		tmp["properties"]["plausibility"] = hotspot.plausibility
		tmp["properties"]["image"] = html.escape(hotspot.image)
		tmp["properties"]["url"] = html.escape(hotspot.url)
		tmp["properties"]["category"] = hotspot.category
		data["features"].append(tmp)

	return HttpResponse(status=200, content_type="application/json",
		content=JSONRenderer().render(data))

def api_hotspot(request):

	if is_ratelimited(request, key="ip", rate=API_REQUEST_LIMIT, group="api", increment=True):
		return HttpResponse(status=429)

	if "uuid" in request.GET:
		uuid = request.GET["uuid"]
	else:
		return HttpResponse(status=404)

	hotspot = models.HotspotModel.objects.filter(uuid=uuid).first()
	if hotspot is None:
		return HttpResponse(status=404)

	return HttpResponse(status=200, content_type="application/json",
		content=JSONRenderer().render(serializers.HotspotSerializer(hotspot).data))

def api_hotspot_content(request):

	if is_ratelimited(request, key="ip", rate=API_REQUEST_LIMIT, group="api", increment=True):
		return HttpResponse(status=429)

	if "uuid" in request.GET:
		uuid = request.GET["uuid"]
	else:
		return HttpResponse(status=404)

	hotspot = models.HotspotModel.objects.filter(uuid=uuid).first()
	if hotspot is None:
		return HttpResponse(status=404)

	return TemplateResponse(request, "details.html", {"hotspot":hotspot})

def api_clusters(request):

	if is_ratelimited(request, key="ip", rate=API_REQUEST_LIMIT, group="api", increment=True):
		return HttpResponse(status=429)

	clusters = models.ClusterModel.objects.all()

	data = {}
	data["type"] = "FeatureCollection"
	data["features"] = []

	for cluster in clusters:

		tmp = {}
		tmp["type"] = "Feature"
		tmp["geometry"] = {}
		tmp["geometry"]["type"] = "Point"
		tmp["geometry"]["coordinates"] = [cluster.geo_long, cluster.geo_lat]
		tmp["properties"] = {}
		data["features"].append(tmp)

	return HttpResponse(status=200, content_type="application/json",
		content=JSONRenderer().render(data))

def api_clusters_grid(request):

	if is_ratelimited(request, key="ip", rate=API_REQUEST_LIMIT, group="api", increment=True):
		return HttpResponse(status=429)

	data = {}
	data["type"] = "FeatureCollection"
	data["features"] = []

	geo_lat = decimal.Decimal(-90)

	while True:
		tmp = {}
		tmp["type"] = "Feature"
		tmp["geometry"] = {}
		tmp["geometry"]["type"] = "LineString"
		tmp["geometry"]["coordinates"] = [
			[-180-models.CLUSTER_WIDTH_HALF, geo_lat-models.CLUSTER_HEIGHT_HALF],
			[ 180-models.CLUSTER_WIDTH_HALF, geo_lat-models.CLUSTER_HEIGHT_HALF]]
		data["features"].append(tmp)
		geo_lat += models.CLUSTER_HEIGHT
		if geo_lat > 90: break

	geo_long = decimal.Decimal(-180)

	while True:
		tmp = {}
		tmp["type"] = "Feature"
		tmp["geometry"] = {}
		tmp["geometry"]["type"] = "LineString"
		tmp["geometry"]["coordinates"] = [
			[geo_long-models.CLUSTER_WIDTH_HALF, -90-models.CLUSTER_HEIGHT_HALF],
			[geo_long-models.CLUSTER_WIDTH_HALF,  90-models.CLUSTER_HEIGHT_HALF]]
		data["features"].append(tmp)
		geo_long += models.CLUSTER_WIDTH
		if geo_long > 180: break

	return HttpResponse(status=200, content_type="application/json",
		content=JSONRenderer().render(data))

def api_hotspots_area(request):

	if is_ratelimited(request, key="ip", rate=API_REQUEST_LIMIT, group="api", increment=True):
		return HttpResponse(status=429)

	geo_lat = None
	geo_long = None
	geo_lat2 = None
	geo_long2 = None
	filter = []

	if "geo_lat" in request.GET:
		geo_lat = decimal.Decimal(request.GET["geo_lat"])
	if "geo_long" in request.GET:
		geo_long = decimal.Decimal(request.GET["geo_long"])
	if "geo_lat2" in request.GET:
		geo_lat2 = decimal.Decimal(request.GET["geo_lat2"])
	if "geo_long2" in request.GET:
		geo_long2 = decimal.Decimal(request.GET["geo_long2"])
	if "filter" in request.GET:
		if len(request.GET["filter"]) is not 0:
			filter = [ int(x) for x in request.GET["filter"].split(",") ]

	if (geo_lat is None) or (geo_long is None) or \
		(geo_lat2 is None)  or (geo_long2 is None):
		return HttpResponse(status=404)

	# get center geo location
	geo_lat_center = round((geo_lat + geo_lat2) / 2, models.CLUSTER_HEIGHT_ROUND)
	geo_long_center = round((geo_long + geo_long2) / 2, models.CLUSTER_WIDTH_ROUND)

	# get corner geo location
	geo_lat2 = round(geo_lat2, models.CLUSTER_HEIGHT_ROUND)
	geo_long2 = round(geo_long2, models.CLUSTER_WIDTH_ROUND)

	# get size of view in cluster units
	n_height = math.ceil(abs(geo_lat-geo_lat2)/models.CLUSTER_HEIGHT)
	n_width = math.ceil(abs(geo_long-geo_long2)/models.CLUSTER_WIDTH)

	clusters_count =  n_width * n_height

	if clusters_count <= models.CLUSTERS_LIMIT:

		update = clusters_count <= models.CLUSTERS_UPDATE
		cluster_center = cl.get_cluster(geo_lat_center, geo_long_center, update)
		clusters = cl.get_clusters(
			cluster_center,
			math.ceil((n_width)/2), math.ceil((n_height)/2),
			update)

	else: clusters = []

	data = {}
	data["type"] = "FeatureCollection"
	data["features"] = []

	for cluster in clusters:

		#------------------------------
		# FOR TESTING ONLY
		#tmp = {}
		#tmp["type"] = "Feature"
		#tmp["geometry"] = {}
		#tmp["geometry"]["type"] = "Point"
		#tmp["geometry"]["coordinates"] = [cluster.geo_long, cluster.geo_lat]
		#tmp["properties"] = {}
		#data["features"].append(tmp)
		#continue
		#------------------------------

		# filter for categories
		if len(filter) is 0: hotspots = cluster.hotspots.all()
		else: hotspots = cluster.hotspots.filter(category__in=filter)

		# order by score and limit to hotspots per cluster
		#if hotposts_per_cluster is -1: hotspots = hotspots.order_by("score")
		#else: hotspots = hotspots.order_by("score")[:hotposts_per_cluster]

		hotspots = hotspots.order_by("score")

		for hotspot in hotspots:

			tmp = {}
			tmp["type"] = "Feature"
			tmp["geometry"] = {}
			tmp["geometry"]["type"] = "Point"
			tmp["geometry"]["coordinates"] = [hotspot.geo_long, hotspot.geo_lat]
			
			tmp["properties"] = {}
			tmp["properties"]["name"] = html.escape(hotspot.name)
			tmp["properties"]["uuid"] = str(hotspot.uuid)
			tmp["properties"]["desc"] = html.escape(hotspot.desc)
			tmp["properties"]["score"] = hotspot.score
			tmp["properties"]["plausibility"] = hotspot.plausibility
			tmp["properties"]["image"] = html.escape(hotspot.image)
			tmp["properties"]["url"] = html.escape(hotspot.url)
			tmp["properties"]["category"] = hotspot.category

			data["features"].append(tmp)

	return HttpResponse(status=200, content_type="application/json",
		content=JSONRenderer().render(data))

hotspot/templates/base.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<title>Hotspot</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script type="text/javascript" src="/static/bower_components/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/bower_components/bootstrap/dist/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="/static/ressources/style.css">
	<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.41.0/mapbox-gl.js'></script>
	<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.41.0/mapbox-gl.css' rel='stylesheet' />
	<link href='/static/ressources/spinner.css' rel='stylesheet' />
	<script src='/static/ressources/spinner.js'></script>
	<script src='/static/ressources/hotspot_api.js'></script>
	<script src='/static/ressources/details.js'></script>
	<script src='/static/ressources/filter.js'></script>
</head>

<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<input type="image" src="/static/ressources/filter-symbol.png" id="menu-toggle" class="button-filter"/>
				<h1 class="navbar-heading">Hotspot</h1>
			</div>
		</div>
	</nav>

	<div id="wrapper" class="toggled">
		<div class="container-fluid">
			<!-- Sidebar -->
			<div id="sidebar-wrapper">
				<ul class="sidebar-nav">
					<li class="sidebar-brand">
						<br>
					</li>
					<li class="sidebar-brand">
						<span class="glyphicon 	glyphicon glyphicon-map-marker" aria-hidden="true"></span> Filter
					</li>
					<li>
						<a id="filter-all" href="#">
							<span class="label label-default all-bg" style="border-radius:15px;">&nbsp;</span>&nbsp;
							All
						</a>
					</li>
					<li>
						<a id="filter-food" href="#">
							<span class="label label-default food-bg" style="border-radius:15px;">&nbsp;</span>&nbsp;
							Food & Restaurants
						</a>
					</li>
					<li>
						<a id="filter-hotels" href="#">
							<span class="label label-default hotel-bg" style="border-radius:15px;">&nbsp;</span>&nbsp;
							Hotels
						</a>
					</li>
					<li>
						<a id="filter-entertainment" href="#">
							<span class="label label-default entertainment-bg" style="border-radius:15px;">&nbsp;</span>&nbsp;
							Entertainment & Arts
						</a>
					</li>
					<li>
						<a id="filter-shops" href="#">
							<span class="label label-default shop-bg" style="border-radius:15px;">&nbsp;</span>&nbsp;
							Shops
						</a>
					</li>
					<li>
						<a id="filter-travel" href="#">
							<span class="label label-default travel-bg" style="border-radius:15px;">&nbsp;</span>&nbsp;
							Travel
						</a>
					</li>
					<hr width="90%">
					<li>
						<button type="button" class="btn btn-danger btn-square center-block" data-toggle="modal" data-target="#hotspot-list-modal">Show Hotspot List</button>
					</li>
				</ul>
			</div>
		</div>

		<script>
			$("#menu-toggle").click(function(e) {
				e.preventDefault();
				$("#wrapper").toggleClass("toggled");
			});
		</script>

	</div>

	<div id="map"></div>
	<script src='/static/ressources/map.js'></script>

	<!-- Modal -->
	<div class="modal fade" id="hotspot-list-modal" role="dialog">
		<div class="modal-dialog">

			<!-- Modal content -->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Hotspot List</h4>
				</div>

				<div class="modal-body">
					<table class="table table-striped" id="hotspot-list-table"></table>
				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
			<script src='/static/ressources/hotspot_list_modal.js'></script>
		</div>
	</div>

</body>
</html>

hotspot/templates/details.html
<div id="details" class="modal fade" role="dialog">
	<script type="text/javascript">$("#details").modal("show");</script>

	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<div class="row">
					{% if hotspot.image %}
					<div class="col-sm-2 text-center">
						<img src="{{hotspot.image}}" class="img-fluid">
					</div>
					<div class="col-sm-10">
						<h2 class="modal-title"><b>{{hotspot.name}}</b></h2>
						<span class="label label-default">{{hotspot.get_category_display}}</span>
					</div>
					{% else %}
					<div class="col text-center">
						<h2 class="modal-title"><b>{{hotspot.name}}</b></h2>
						<span class="label label-default">{{hotspot.get_category_display}}</span>
					</div>
					{% endif %}
				</div>
				<div class="row">
					<div class="col-sm-4 text-center" style="padding: 5px;">
						<b>Score: {{hotspot.score}}</b>
					</div>
					<div class="col-sm-4 text-center" style="padding: 5px;">
						<b>{{hotspot.geo_lat}}, {{hotspot.geo_long}}</b>
					</div>
					<div class="col-sm-4 text-center" style="padding: 5px;">
						<!--<b>Plausibility: {{hotspot.plausibility}}</b>-->
					</div>
				</div>
				<div class="row">
					<div class="col text-center" style="padding: 5px;">
						{% if hotspot.country %} {{hotspot.country}} {% endif %}
						{% if hotspot.city %} {{hotspot.city}} {% endif %},
						{% if hotspot.zip %} {{hotspot.zip}} {% endif %}
						{% if hotspot.street %} {{hotspot.street}} {% endif %}
					</div>
				</div>
			</div>
			<div class="modal-body">
				{% if hotspot.desc %}
				<div class="row">
					<div class="col text-center" style="padding: 5px;">
						<p>{{hotspot.desc}}</p>
					</div>
				</div>
				{% endif %}
				<div class="row">
					<div class="col text-center" style="padding: 5px;">
						<div class="btn-group">
							{% if hotspot.phone %}
							<button class='btn btn-primary' onclick="window.open('tel:{{hotspot.phone}}','_blank');">Phone</button>
							{% endif %}
							{% if hotspot.url %}
							<button class='btn btn-primary' onclick="redirect_safe('{{hotspot.url}}');">Homepage</button>
							{% endif %}
							{% if hotspot.url_fb %}
							<button class='btn btn-primary' onclick="window.location.href='{{hotspot.url_fb}}';">Facebook</button>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>

	</div>
</div>

<script>


</script>

hotspot/templates/index.html
{% extends "base.html" %}

{% block content %}

{% endblock %}